name: Deployment

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configuring SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key

          # Debug: Show the contents of the SSH key file
          echo "SSH key contents:"
          cat ~/.ssh/production.key || echo "SSH key file not found or empty"

          # Create SSH config file
          echo "Creating SSH config file..."
          cat > ~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            Port $SSH_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END

          # Debug: Show the contents of the SSH config file
          echo "SSH config contents:"
          cat ~/.ssh/config || echo "SSH config file not found or empty"

          # Debug: Test SSH connection
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/production.key $SSH_USER@$SSH_HOST 'echo "SSH connection successful"'

          # Debug: Show SSH key fingerprints
          echo "SSH key fingerprints:"
          ssh-keygen -y -f ~/.ssh/production.key || echo "Failed to generate SSH key fingerprints"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Update code
        run: |
          ssh production "cd $PROJECT_DIR &&
            git stash --include-untracked > /dev/null &&
            git checkout master &&
            git pull"
        env:
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
