name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> "$HOME/.ssh/known_hosts"
        env:
          SSH_HOST: ${{ variables.SSH_HOST }}

      - name: Deploy with rsync
        run: |
          rsync -e "ssh -p ${{ variables.SSH_PORT }} -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete ./ ${{ variables.REPO_USER }}@${{ variables.SSH_HOST }}:${{ variables.REPO_NAME }}
